name: flutter_landing_page
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  freezed_annotation:
  gap:
  provider:
  responsive_framework:
  riverpod_annotation:
  shadcn_ui:
  websafe_svg:

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_test:
    sdk: flutter
  freezed:
  pedantic_mono:
  riverpod_generator:
  riverpod_lint:

flutter:
  uses-material-design: true
  assets:
    - assets/
