name: flutter_lp_playground
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold:
  gap:

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:

flutter:
  uses-material-design: true
